In [7]:
import pandas as pd

In [12]:
veri=pd.read_csv('student-mat.csv',sep=';')

In [13]:
veri=veri[['G1','G2','G3','studytime','failures','absences','age']]

In [14]:
veri.head()

G1  G2  G3  studytime  failures  absences  age
0   5   6   6          2         0         6   18
1   5   5   6          2         0         4   17
2   7   8  10          2         3        10   15
3  15  14  15          3         0         2   15
4   6  10  10          2         0         4   16

In [16]:
veri.dtypes

G1           int64
G2           int64
G3           int64
studytime    int64
failures     int64
absences     int64
age          int64
dtype: object

In [18]:
import numpy as np
y=np.array(veri['G3'])
X=veri.drop('G3',axis=1)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [22]:
from sklearn.linear_model import LinearRegression

In [23]:
linear=LinearRegression()

In [24]:
linear.fit(X_train,y_train)

LinearRegression()

In [25]:
linear.score(X_test,y_test)

0.8325898318712225

In [26]:
linear.score(X_train,y_train)

0.8261275475197141

In [27]:
print('linear_k: \n',linear.coef_)
print('linear_i: \n',linear.intercept_)

linear_k: 
 [ 0.19575962  0.95558174 -0.24215827  0.12730705  0.03566925 -0.23224281]
linear_i: 
 2.154909740675155


In [28]:
veri.head()

G1  G2  G3  studytime  failures  absences  age
0   5   6   6          2         0         6   18
1   5   5   6          2         0         4   17
2   7   8  10          2         3        10   15
3  15  14  15          3         0         2   15
4   6  10  10          2         0         4   16

In [32]:
new_data=np.array([[15,14,3,0,2,15]])
linear.predict(new_data)

array([14.33066999])

In [33]:
new_data2=np.array([[6,10,2,0,4,15]])
linear.predict(new_data2)

array([9.06000317])