In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
import warnings

warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('test1.csv')

In [5]:
df.shape

(43201, 84)

In [6]:
df

time  P1_B2004  P1_B2016   P1_B3004    P1_B3005  \
0      2020-07-07 15:00:00   0.10178   1.58771  403.78854   985.37353   
1      2020-07-07 15:00:01   0.10178   1.58725  403.78854   985.37353   
2      2020-07-07 15:00:02   0.10178   1.59519  403.78854   985.37353   
3      2020-07-07 15:00:03   0.10178   1.59747  403.78854   985.37353   
4      2020-07-07 15:00:04   0.10178   1.59869  403.78854   985.37353   
...                    ...       ...       ...        ...         ...   
43196  2020-07-08 02:59:56   0.10109   1.61632  395.43826  1115.26257   
43197  2020-07-08 02:59:57   0.10109   1.61891  395.43826  1115.26257   
43198  2020-07-08 02:59:58   0.10109   1.61815  395.43826  1115.26257   
43199  2020-07-08 02:59:59   0.10109   1.62609  395.43826  1115.26257   
43200  2020-07-08 03:00:00   0.10109   1.63081  395.43826  1115.26257   

       P1_B4002   P1_B4005    P1_B400B  P1_B4022  P1_FCV01D  ...  P4_ST_GOV  \
0      32.59527  100.00000  2839.58520  36.81010  100.00000  ...    20469.0   
1      32.59527  100.00000  2843.37549  36.80895  100.00000  ...    20489.0   
2      32.59527  100.00000  2845.06006  36.82879  100.00000  ...    20604.0   
3      32.59527  100.00000  2837.33911  36.83451  100.00000  ...    20633.0   
4      32.59527  100.00000  2843.37549  36.83756  100.00000  ...    20738.0   
...         ...        ...         ...       ...        ...  ...        ...   
43196  31.81634   79.42770  2440.14233  36.10442   37.51368  ...    21044.0   
43197  31.81634   79.52109  2455.06909  36.11090   37.72263  ...    21073.0   
43198  31.81634   79.62234  2446.70361  36.10899   37.83055  ...    21064.0   
43199  31.81634   79.71570  2444.73511  36.12883   37.67564  ...    21171.0   
43200  31.81634   79.81714  2459.82617  36.14066   37.76140  ...    21112.0   

        P4_ST_LD   P4_ST_PO  P4_ST_PS  P4_ST_PT01  P4_ST_TT01  attack  \
0      386.26666  380.31683         0     10044.0     27567.0       0   
1      386.30286  380.02747         0     10040.0     27564.0       0   
2      389.73883  381.52850         0     10037.0     27565.0       0   
3      388.94311  382.08911         0     10040.0     27560.0       0   
4      389.72082  383.44543         0     10042.0     27564.0       0   
...          ...        ...       ...         ...         ...     ...   
43196  394.91107  390.13672        50     10053.0     27593.0       0   
43197  397.35248  390.24518        50     10053.0     27599.0       0   
43198  396.70142  390.46222        50     10052.0     27599.0       0   
43199  397.73218  391.78241        50     10053.0     27603.0       0   
43200  397.24390  391.31219        50     10053.0     27595.0       0   

       attack_P1  attack_P2  attack_P3  
0              0          0          0  
1              0          0          0  
2              0          0          0  
3              0          0          0  
4              0          0          0  
...          ...        ...        ...  
43196          0          0          0  
43197          0          0          0  
43198          0          0          0  
43199          0          0          0  
43200          0          0          0  

[43201 rows x 84 columns]

In [7]:
df.columns 

Index(['time', 'P1_B2004', 'P1_B2016', 'P1_B3004', 'P1_B3005', 'P1_B4002',
       'P1_B4005', 'P1_B400B', 'P1_B4022', 'P1_FCV01D', 'P1_FCV01Z',
       'P1_FCV02D', 'P1_FCV02Z', 'P1_FCV03D', 'P1_FCV03Z', 'P1_FT01',
       'P1_FT01Z', 'P1_FT02', 'P1_FT02Z', 'P1_FT03', 'P1_FT03Z', 'P1_LCV01D',
       'P1_LCV01Z', 'P1_LIT01', 'P1_PCV01D', 'P1_PCV01Z', 'P1_PCV02D',
       'P1_PCV02Z', 'P1_PIT01', 'P1_PIT02', 'P1_PP01AD', 'P1_PP01AR',
       'P1_PP01BD', 'P1_PP01BR', 'P1_PP02D', 'P1_PP02R', 'P1_STSP', 'P1_TIT01',
       'P1_TIT02', 'P2_24Vdc', 'P2_ASD', 'P2_AutoGO', 'P2_CO_rpm', 'P2_Emerg',
       'P2_HILout', 'P2_MSD', 'P2_ManualGO', 'P2_OnOff', 'P2_RTR', 'P2_SIT01',
       'P2_SIT02', 'P2_TripEx', 'P2_VT01', 'P2_VTR01', 'P2_VTR02', 'P2_VTR03',
       'P2_VTR04', 'P2_VXT02', 'P2_VXT03', 'P2_VYT02', 'P2_VYT03', 'P3_FIT01',
       'P3_LCP01D', 'P3_LCV01D', 'P3_LH', 'P3_LIT01', 'P3_LL', 'P3_PIT01',
       'P4_HT_FD', 'P4_HT_LD', 'P4_HT_PO', 'P4_HT_PS', 'P4_LD', 'P4_ST_FD',
       'P4_ST_GOV', 

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43201 entries, 0 to 43200
Data columns (total 84 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   time         43201 non-null  object 
 1   P1_B2004     43201 non-null  float64
 2   P1_B2016     43201 non-null  float64
 3   P1_B3004     43201 non-null  float64
 4   P1_B3005     43201 non-null  float64
 5   P1_B4002     43201 non-null  float64
 6   P1_B4005     43201 non-null  float64
 7   P1_B400B     43201 non-null  float64
 8   P1_B4022     43201 non-null  float64
 9   P1_FCV01D    43201 non-null  float64
 10  P1_FCV01Z    43201 non-null  float64
 11  P1_FCV02D    43201 non-null  float64
 12  P1_FCV02Z    43201 non-null  float64
 13  P1_FCV03D    43201 non-null  float64
 14  P1_FCV03Z    43201 non-null  float64
 15  P1_FT01      43201 non-null  float64
 16  P1_FT01Z     43201 non-null  float64
 17  P1_FT02      43201 non-null  float64
 18  P1_FT02Z     43201 non-null  float64
 19  P1_F

In [9]:
X=df.drop(['time','P2_24Vdc', 'P2_ASD', 'P2_AutoGO', 'P2_CO_rpm', 'P2_Emerg',
       'P2_HILout', 'P2_MSD', 'P2_ManualGO', 'P2_OnOff', 'P2_RTR', 'P2_SIT01',
       'P2_SIT02', 'P2_TripEx', 'P2_VT01', 'P2_VTR01', 'P2_VTR02', 'P2_VTR03',
       'P2_VTR04', 'P2_VXT02', 'P2_VXT03', 'P2_VYT02', 'P2_VYT03', 'P3_FIT01',
       'P3_LCP01D', 'P3_LCV01D', 'P3_LH', 'P3_LIT01', 'P3_LL', 'P3_PIT01',
       'P4_HT_FD', 'P4_HT_LD', 'P4_HT_PO', 'P4_HT_PS', 'P4_LD', 'P4_ST_FD',
       'P4_ST_GOV', 'P4_ST_LD', 'P4_ST_PO', 'P4_ST_PS', 'P4_ST_PT01',
       'P4_ST_TT01', 'attack', 'attack_P1', 'attack_P2', 'attack_P3'],axis=1)
y=df['attack_P1']

In [10]:
X

P1_B2004  P1_B2016   P1_B3004    P1_B3005  P1_B4002   P1_B4005  \
0       0.10178   1.58771  403.78854   985.37353  32.59527  100.00000   
1       0.10178   1.58725  403.78854   985.37353  32.59527  100.00000   
2       0.10178   1.59519  403.78854   985.37353  32.59527  100.00000   
3       0.10178   1.59747  403.78854   985.37353  32.59527  100.00000   
4       0.10178   1.59869  403.78854   985.37353  32.59527  100.00000   
...         ...       ...        ...         ...       ...        ...   
43196   0.10109   1.61632  395.43826  1115.26257  31.81634   79.42770   
43197   0.10109   1.61891  395.43826  1115.26257  31.81634   79.52109   
43198   0.10109   1.61815  395.43826  1115.26257  31.81634   79.62234   
43199   0.10109   1.62609  395.43826  1115.26257  31.81634   79.71570   
43200   0.10109   1.63081  395.43826  1115.26257  31.81634   79.81714   

         P1_B400B  P1_B4022  P1_FCV01D  P1_FCV01Z  ...  P1_PIT02  P1_PP01AD  \
0      2839.58520  36.81010  100.00000   99.91608  ...   0.27557     540833   
1      2843.37549  36.80895  100.00000   99.91608  ...   0.27710     540833   
2      2845.06006  36.82879  100.00000   99.91608  ...   0.27710     540833   
3      2837.33911  36.83451  100.00000   99.91608  ...   0.27557     540833   
4      2843.37549  36.83756  100.00000   99.90845  ...   0.27710     540833   
...           ...       ...        ...        ...  ...       ...        ...   
43196  2440.14233  36.10442   37.51368   37.21771  ...   0.82565     540833   
43197  2455.06909  36.11090   37.72263   37.21008  ...   0.82565     540833   
43198  2446.70361  36.10899   37.83055   37.21771  ...   0.82642     540833   
43199  2444.73511  36.12883   37.67564   37.21771  ...   0.82260     540833   
43200  2459.82617  36.14066   37.76140   37.21771  ...   0.82489     540833   

       P1_PP01AR  P1_PP01BD  P1_PP01BR  P1_PP02D  P1_PP02R  P1_STSP  P1_TIT01  \
0         540833          0          0         1         1        1  34.88770   
1         540833          0          0         1         1        1  34.88770   
2         540833          0          0         1         1        1  34.88770   
3         540833          0          0         1         1        1  34.88770   
4         540833          0          0         1         1        1  34.90295   
...          ...        ...        ...       ...       ...      ...       ...   
43196     540833          0          0         1         1        1  35.22338   
43197     540833          0          0         1         1        1  35.23864   
43198     540833          0          0         1         1        1  35.23864   
43199     540833          0          0         1         1        1  35.25391   
43200     540833          0          0         1         1        1  35.22338   

       P1_TIT02  
0      35.14710  
1      35.14710  
2      35.14710  
3      35.14710  
4      35.14710  
...         ...  
43196  35.60485  
43197  35.63538  
43198  35.60485  
43199  35.62011  
43200  35.60485  

[43201 rows x 38 columns]

In [11]:
y

0        0
1        0
2        0
3        0
4        0
        ..
43196    0
43197    0
43198    0
43199    0
43200    0
Name: attack_P1, Length: 43201, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
X_train.dtypes

P1_B2004     float64
P1_B2016     float64
P1_B3004     float64
P1_B3005     float64
P1_B4002     float64
P1_B4005     float64
P1_B400B     float64
P1_B4022     float64
P1_FCV01D    float64
P1_FCV01Z    float64
P1_FCV02D    float64
P1_FCV02Z    float64
P1_FCV03D    float64
P1_FCV03Z    float64
P1_FT01      float64
P1_FT01Z     float64
P1_FT02      float64
P1_FT02Z     float64
P1_FT03      float64
P1_FT03Z     float64
P1_LCV01D    float64
P1_LCV01Z    float64
P1_LIT01     float64
P1_PCV01D    float64
P1_PCV01Z    float64
P1_PCV02D    float64
P1_PCV02Z    float64
P1_PIT01     float64
P1_PIT02     float64
P1_PP01AD      int64
P1_PP01AR      int64
P1_PP01BD      int64
P1_PP01BR      int64
P1_PP02D       int64
P1_PP02R       int64
P1_STSP        int64
P1_TIT01     float64
P1_TIT02     float64
dtype: object

In [14]:
X_train.shape

(34560, 38)

In [15]:
X_test


P1_B2004  P1_B2016   P1_B3004    P1_B3005  P1_B4002   P1_B4005  \
15313   0.10049   1.32183  406.61285  1057.21838  32.96325   91.03789   
10982   0.10049   1.36807  406.61285  1057.21838  32.96325  100.00000   
34147   0.10109   1.25270  395.43826  1115.26257  31.81634  100.00000   
28889   0.10109   1.38591  395.43826  1115.26257  31.81634    0.00000   
1007    0.10178   1.59373  403.78854   985.37353  32.59527  100.00000   
...         ...       ...        ...         ...       ...        ...   
15688   0.10049   1.18527  406.61285  1057.21838  32.96325   84.12187   
35807   0.10109   1.60301  395.43826  1115.26257  31.81634  100.00000   
15448   0.10049   1.35922  406.61285  1057.21838  32.96325   88.70673   
20983   0.10177   1.34905  394.21475  1086.26758  32.43124  100.00000   
24741   0.10177   1.46578  394.21475  1086.26758  32.43124  100.00000   

         P1_B400B  P1_B4022  P1_FCV01D  P1_FCV01Z  ...  P1_PIT02  P1_PP01AD  \
15313  2831.72388  36.51661  100.00000   99.79400  ...   0.27557     540833   
10982  2853.18994  36.63220  100.00000   99.80164  ...   0.27634     540833   
34147  2835.51392  35.19537  100.00000   99.95309  ...   0.27481     540833   
28889    36.94299  35.52840    0.00000    0.28381  ...   0.20462     540833   
1007   2837.47949  36.82516  100.00000   99.91989  ...   0.27596     540833   
...           ...       ...        ...        ...  ...       ...        ...   
15688  2842.39282  36.17519   90.52824   91.43219  ...   0.27481     540833   
35807  2828.07385  36.07113  100.00000   99.42293  ...   0.27481     540833   
15448  2848.28857  36.61007   99.24728   99.79400  ...   0.27710     540833   
20983  2833.96997  36.04945  100.00000   99.13760  ...   0.27557     540833   
24741  2838.18115  36.34128  100.00000   99.81178  ...   0.27710     540833   

       P1_PP01AR  P1_PP01BD  P1_PP01BR  P1_PP02D  P1_PP02R  P1_STSP  P1_TIT01  \
15313     540833          0          0         1         1        1  36.68823   
10982     540833          0          0         1         1        1  35.14710   
34147     540833          0          0         1         1        1  35.00976   
28889     540833          0          0         1         1        1  35.74219   
1007      540833          0          0         1         1        1  34.83429   
...          ...        ...        ...       ...       ...      ...       ...   
15688     540833          0          0         1         1        1  36.64245   
35807     540833          0          0         1         1        1  35.35690   
15448     540833          0          0         1         1        1  36.70349   
20983     540833          0          0         1         1        1  35.46753   
24741     540833          0          0         1         1        1  34.76562   

       P1_TIT02  
15313  37.31384  
10982  35.42175  
34147  35.33019  
28889  37.83263  
1007   35.56671  
...         ...  
15688  37.10022  
35807  37.55799  
15448  37.22229  
20983  35.74219  
24741  35.00976  

[8641 rows x 38 columns]

In [16]:
from sklearn.naive_bayes import GaussianNB


# instantiate the model
gnb = GaussianNB()


# fit the model
gnb.fit(X_train, y_train)

GaussianNB()

In [17]:
y_pred = gnb.predict(X_test)

y_pred

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 0.7482


In [19]:
y_pred_train = gnb.predict(X_train)

y_pred_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.7484


In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)

print('\nTrue Positives(TP) = ', cm[0,0])

print('\nTrue Negatives(TN) = ', cm[1,1])

print('\nFalse Positives(FP) = ', cm[0,1])

print('\nFalse Negatives(FN) = ', cm[1,0])

Confusion matrix

 [[6376 2176]
 [   0   89]]

True Positives(TP) =  6376

True Negatives(TN) =  89

False Positives(FP) =  2176

False Negatives(FN) =  0
